# Generated by Django 5.2.8 on 2025-11-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('claimed', 'Claimed')], default='lost', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
